unit TestValidateRegisterRESTControllers;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Web.HTTPApp, System.Generics.Collections, Spring.Services,
  MVCFramework.Commons, MVCFramework, RESTFull.Web.Module, System.Classes;

type
  // Test methods for class TRESTFullWebModule

  TestTRESTFullWebModule = class(TTestCase)
  strict private
    FRESTFullWebModule: TRESTFullWebModule;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestWebModuleCreate;
    procedure TestWebModuleDestroy;
  end;

implementation

procedure TestTRESTFullWebModule.SetUp;
begin
  FRESTFullWebModule := TRESTFullWebModule.Create(nil);
end;

procedure TestTRESTFullWebModule.TearDown;
begin
  FRESTFullWebModule.Free;
  FRESTFullWebModule := nil;
end;

procedure TestTRESTFullWebModule.TestWebModuleCreate;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FRESTFullWebModule.WebModuleCreate(Sender);
  // TODO: Validate method results
end;

procedure TestTRESTFullWebModule.TestWebModuleDestroy;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FRESTFullWebModule.WebModuleDestroy(Sender);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTRESTFullWebModule.Suite);
end.

