unit Pessoa;

interface

uses
  Spring.Persistence.Mapping.Attributes;

type

  [Entity]
  [Table('pessoa')]
  TPessoa = class
  strict private
    FId: Int64;
    FNome: string;
    FCpfCnpj:string;
  public
    [AutoGenerated]
    [Column('id', [cpPrimaryKey, cpRequired, cpNotNull])]
    property Id: Int64 read fId write fId;

    [Column('nome', [cpRequired, cpNotNull])]
    property Nome: string read fNome write fNome;

    [Column('cpfcnpj', [cpRequired, cpNotNull])]
    property CpfCnpj: string read FCpfCnpj write FCpfCnpj;
  end;

implementation

end.
